import type { Metadata } from "next";

import "./globals.scss";
import { manrope } from "@/utils";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "HUST Elearning App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;

  const content = (
    <html lang="en">
      <body className={manrope.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ToastContainer
            autoClose={2000}
            position="top-right"
          />
        </ThemeProvider>
      </body>
    </html>
  );

  if (!clerkPublishableKey) {
    // During local dev or CI builds the key may be missing; avoid throwing
    // a generic clerk error during prerender and give a helpful message.
    // Note: Authentication features will not work without this env var.
    // Set `NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY` in your environment or
    // deployment settings (e.g. Vercel Project > Environment Variables).
    // eslint-disable-next-line no-console
    console.warn(
      'Missing NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: Clerk UI will be disabled.\n' +
      'Set NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY in your .env.local or deployment settings.'
    );
    return content;
  }

  return (
    <ClerkProvider publishableKey={clerkPublishableKey}>
      {content}
    </ClerkProvider>
  );
}
